# Projekt: proj1 test
# Autor:   Marek Zak
# Datum:   29.10.2016

CC=gcc
CFLAGS=-std=c99 -Wall -Wextra -Werror

proj1: proj1.c
	$(CC) $(CFLAGS) proj1.c -o proj1
	
clean:
	rm -f proj1 proj1.o output

run:
	rm -f output
	chmod +x ob1.sh
	./ob1.sh
